import Head from "next/head";
import { Container, Typography, Box } from "@mui/material";
import { useEffect, useState } from "react";
import LatestPostCard from "~/components/LatestPostCard";
import { api } from "~/utils/api";

export default function Home() {
  const [greetingPrisma, setGreetingPrisma] = useState("Loading data from Prisma...");
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    async function fetchGreeting() {
      try {
        const response = await fetch('/api/trpc/posts');
        if (!response.ok) {
          throw new Error('Failed to fetch the latest post');
        }
        const data = await response.json();
        setGreetingPrisma(data?.name ?? "No name found");
      } catch (error) {
        console.error("Error fetching greeting from API: ", error);
        setGreetingPrisma("Error loading data");
      }
    }

    void fetchGreeting();
  }, []);

  return (
    <>
      <Head>
        <title>Zod First</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg" sx={{ mt: 5 }}>
        <Typography variant="h2" gutterBottom>
          Use <Box component="span" color="primary.main">Zod</Box> with tRPC
        </Typography>
        <Typography variant="body1" gutterBottom>
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </Typography>
        <Typography variant="body1" gutterBottom>
          {greetingPrisma}
        </Typography>
        <Box sx={{ mt: 4 }}>
          <LatestPostCard />
        </Box>
      </Container>
    </>
  );
}
