import Head from "next/head";
import { Container, Typography, Box, Button } from "@mui/material";
import { useEffect, useState } from "react";
import LatestPostCard from "~/components/LatestPostCard";
import { api } from "~/utils/api";

export default function Home() {
  const [greetingPrisma, setGreetingPrisma] = useState("Loading data from Prisma...");
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  useEffect(() => {
    async function fetchGreeting() {
      try {
        const response = await fetch('/api/trpc/posts');
        console.log(response);
        if (!response.ok) {
          throw new Error('Failed to fetch the latest post');
        }
        const data: { name?: string } = await response.json() as { name?: string };
        setGreetingPrisma(data?.name ?? "No name found");
      } catch (error) {
        console.error("Error fetching greeting from API: ", error);
        setGreetingPrisma("Error loading data");
      }
    }

    void fetchGreeting();
  }, []);

  const handleCreatePost = async () => {
    try {
      const response = await fetch('/api/trpc/posts', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name: 'New Post' }),
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Failed to create post: ${errorText}`);
      }
      window.location.reload();
    } catch (error) {
      console.error("Error creating new post: ", error);
    }
  };

  return (
    <>
      <Head>
        <title>Zod First</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg" sx={{ mt: 5 }}>
        <Typography variant="h2" gutterBottom>
          Use <Box component="span" color="primary.main">Zod</Box> with tRPC
        </Typography>
        <Typography variant="body1" gutterBottom>
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </Typography>
        <Typography variant="body1" gutterBottom>
          {greetingPrisma}
        </Typography>
        <Box sx={{ mt: 4 }}>
          <LatestPostCard />
        </Box>
        <Box sx={{ mt: 4, textAlign: 'center' }}>
          <Button variant="contained" color="primary" onClick={handleCreatePost}>
            Create New Post
          </Button>
        </Box>
      </Container>
    </>
  );
}
